on:
  push:
    tags:
      - 'v*'

variables:
  DWC_VERSION: v3.5.3

name: Build MillenniumOS UI for Release
jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout Duet Web Control
        uses: actions/checkout@v4
        with:
          repository: Duet3D/DuetWebControl
          ref: ${{ env.DWC_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src/plugins/MillenniumOS

      - name: Apply plugin version
        run: |
          echo "Applying version ${{ github.ref_name }} to MillenniumOS UI"
          sed -i "s/'"version": "0.0.0"'/'"version": ${{ github.ref_name }}'/g" src/plugins/MillenniumOS/plugin.json

      - name: Build MillenniumOS UI Release
        run: |
          src/plugins/MillenniumOS/dist/release.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: MillenniumOS UI ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            dist/*.zip
