on:
  push:
    tags:
      - 'v*'

env:
  DWC_VERSION: ${{ inputs.dwc_version || 'v3.5.3' }}
  VERSION: ${{ github.ref_name }}

name: Build MillenniumOS UI for Release
jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout Duet Web Control
        uses: actions/checkout@v4
        with:
          repository: Duet3D/DuetWebControl
          ref: ${{ env.DWC_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src/plugins/MillenniumOS_UI

      - name: Strip v from version
        id: strip-version
        run: |
          VERSION=${{ github.ref_name }}
          echo "Stripping v from version $VERSION"
          echo "SHORT_VERSION=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Apply plugin version
        run: |
          echo "Applying version $VERSION to MillenniumOS UI"
          sed -i "s/\"version\": \"0.0.0\"/\"version\": \"${{ steps.strip-version.outputs.short_version }}\"/" src/plugins/MillenniumOS_UI/plugin.json
          cat src/plugins/MillenniumOS_UI/plugin.json
          
      - name: Build Duet Web Control With MOS UI Release # needs to run first to include MOS UI as plugin
        run: |
          src/plugins/MillenniumOS_UI/dist/releaseDwcWithMosUI.sh

      - name: Build MillenniumOS UI Plugin Release
        run: |
          src/plugins/MillenniumOS_UI/dist/releasePlugin.sh
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: MillenniumOS UI ${{ github.ref_name }}
          draft: true
          generate_release_notes: true

      - name: Upload MOS UI Plugin Zip
        id: upload-mos-ui-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/MillenniumOS_UI-${{ steps.strip-version.outputs.short_version }}.zip
          asset_name: MillenniumOS_UI-${{ steps.strip-version.outputs.short_version }}.zip
          asset_content_type: application/zip

      - name: Upload DWC With MOS UI Zip
        id: upload-dwc-with-mos-ui-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: distDWC/DuetWebControl-SD.zip
          asset_name: DuetWebControl-SD-${{ env.DWC_VERSION }}-with-mosUI.zip
          asset_content_type: application/zip

